MockUp/Models/Examen.cs
using MockUp.Models;

namespace MockUp.Models
{
    public class Examen
    {
       public string DescPregunta { get; set; }
            public string DescRespuesta { get; set; }
            public int IdPregunta { get; set; }
            public int IdOpcion { get; set; }
            public bool EsCorrecta {  get; set; }
            public int? OpcionResp { get; set; }
            public int? Confianza { get; set; }
            public int? Calificacion { get; set; }

    }
}

MockUp/Controllers/CuestionarioAlumnosController.cs
using Microsoft.AspNetCore.Mvc;
using MockUp.Models;
using System.Data.SqlClient;
using MockUp.Helper;
namespace MockUp.Controllers
{
    public class CuestionarioAlumnosController : Controller
    {
        [Route("/Temas")]
        public IActionResult Temas()
        {
            string userCorreo = HttpContext.Session.GetString("_UserCorreo"); // Recupero el correo de la sesión
            string userType = "Alumno"; // Tipo de usuario alumno
            List<TemasModel> listTemas = new List<TemasModel>(); //lista de temas para el alumno
            //conexcion a la base de datos
            using(var connection = new SqlConnection(ConnectionHelper.GetConnectionString()))
            {
                connection.Open();
                //Creo un procedimiento
                using(var command = new SqlCommand())
                {
                    command.Connection = connection;
                    command.CommandText = "dbo.mostrarTemas"; //Obtengo el nombre del procedimiento
                    command.CommandType = System.Data.CommandType.StoredProcedure;
                    command.Parameters.AddWithValue("@Correo", userCorreo);
                    command.Parameters.AddWithValue("@UserType", userType);
                    using (SqlDataReader reader = command.ExecuteReader()) //leo los datos
                    {
                        while (reader.Read())
                        {
                            Models.TemasModel temas = new Models.TemasModel();
                            temas.IdTema = Convert.ToInt32(reader["IdTema"]);
                            temas.Tema = reader["Tema"].ToString();//leo la columa de mi tabla 
                            temas.LinkImagen = reader["LinkImagen"].ToString();
                            temas.Calificacion = Convert.ToInt32(reader["Calificacion"]);
                            listTemas.Add(temas);//se guarda en la lista
                        }
                    }
                }
                connection.Close();
            }
            return View(listTemas);
        }
    }
}

MockUp/Controllers/ExamenAlumnoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MockUp.Models;
using MockUp.ViewModel;
using System.Data.SqlClient;
using MockUp.Helper;

namespace MockUp.Controllers
{
    public class ExamenAlumnoController : Controller
    {

        [Route("/Examen/{idTema}")]
        public IActionResult Examen(int idTema)
        {
            string userCorreo = HttpContext.Session.GetString("_UserCorreo"); // Recupero el correo de la sesión
            List<Models.Examen> listaExamen = new List<Models.Examen>(); //Inicio modelo del examen(preguntas y respuestas)
            int? calificacion = null;

            using(var connection = new SqlConnection(ConnectionHelper.GetConnectionString())) //Me conecto a la base de datos
            {
                connection.Open();

                using (var command = connection.CreateCommand())
                {
                    command.Connection = connection;
                    command.CommandText = "dbo.ExamenAlumno";
                    command.CommandType = System.Data.CommandType.StoredProcedure;
                    command.Parameters.AddWithValue("@IdTema", idTema); //Parametro de sql 
                    command.Parameters.AddWithValue("@Correo", userCorreo);

                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            
                           calificacion = reader["Calificacion"] != DBNull.Value ? (int?)Convert.ToInt32(reader["Calificacion"]) : null;
                        }


                        reader.NextResult(); //lee otro select
                        while (reader.Read())
                        {
                            //Leo el select de storedProcedure
                            Models.Examen examen = new Models.Examen();
                            examen.DescPregunta = reader["DescPregunta"].ToString(); 
                            examen.DescRespuesta = reader["DescRespuesta"].ToString();
                            examen.IdPregunta = Convert.ToInt32(reader["IdPregunta"]);
                            examen.IdOpcion = Convert.ToInt32(reader["IdOpcion"]);
                            examen.EsCorrecta = reader.GetBoolean(reader.GetOrdinal("EsCorrecta"));
                            //Para que reciba DBNull 
                            examen.OpcionResp = reader["OpcionResp"] != DBNull.Value ? (int?)Convert.ToInt32(reader["OpcionResp"]) : null;
                            examen.Confianza = reader["Confianza"] != DBNull.Value ? (int?)Convert.ToInt32(reader["Confianza"]) : null;

                            //Guardo el objeto a una lista
                            listaExamen.Add(examen);
                        }
                    }
                }
                connection.Close();
            }
            //Necesita IdTema para saber que examen va a tener
            var model = new ExamenViewModel
            {
                IdTema = idTema,
                Calificacion = calificacion,
                Examen = listaExamen
            };

            return View("Examen",model);
        }

        [HttpPost]
        public IActionResult GuardarRespuestas([FromBody] List<RespuestasModel> respuestas)
        {
            string userCorreo = HttpContext.Session.GetString("_UserCorreo"); //Recupero el correo de la sesion

            if (string.IsNullOrEmpty(userCorreo))
            {
                //Si no encuentra un correo
                return RedirectToAction("Login", "Home");
            }
            using (var connection = new SqlConnection(ConnectionHelper.GetConnectionString()))
            {
                connection.Open();
                foreach (var respuesta in respuestas)
                {
                    using (var command = connection.CreateCommand())
                    {
                        command.Connection = connection;
                        command.CommandText = "dbo.GuardarRespuestas";
                        command.CommandType = System.Data.CommandType.StoredProcedure;
                        command.Parameters.AddWithValue("@Correo", userCorreo);
                        command.Parameters.AddWithValue("@IdPrueba", respuesta.IdPrueba);
                        command.Parameters.AddWithValue("@IdPregunta", respuesta.IdPregunta);
                        command.Parameters.AddWithValue("@IdOpcion", respuesta.IdOpcion);
                        command.Parameters.AddWithValue("@EsCorrecta", respuesta.EsCorrecta);
                        command.Parameters.AddWithValue("@Confianza", respuesta.Confianza);
                        command.ExecuteNonQuery();
                    }
                }
                connection.Close();
            }
            return Ok();



        }
       
    }
}

MockUp/Views/ExamenAlumno/Examen.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Examen</title>
    <link rel="stylesheet" href="~/css/examen.css">
    <link rel="stylesheet" href="~/css/ModalWarning.css">
    <style>
        #guardarRespuestasBtn {
            display: none; /* Ocultar inicialmente */
        }
    </style>
</head>
<body>
    <header>
        <h1>EXAMEN</h1>
    </header>

    <div class="container">
        @{
            int? currentIdPregunta = null;
            var correctas = new Dictionary<int, int>();
            var respuestas = new Dictionary<int, int?>();
            var confianzas = new Dictionary<int, int?>();
        }

        @foreach (var examen in Model.Examen)
        {
            if (examen.IdPregunta != currentIdPregunta)
            {
                if (currentIdPregunta != null)
                {
                    @:<div>
                        <label style="text-align:center; font-weight: bold;">Nivel de confianza:</label>
                        @for (int i = 1; i <= 3; i++)
                        {
                            <label>
                                <input type="radio" name="confianza_@currentIdPregunta" value="@i" onclick="seleccionarConfianza(@currentIdPregunta, @i)" @(confianzas[currentIdPregunta.Value] == i ? "checked" : "") /> @(i == 1 ? "Baja" : i == 2 ? "Media" : "Alta")
                            </label>
                        }
                    @:</div>
                    @:</section>
                }

                currentIdPregunta = examen.IdPregunta;
                respuestas[currentIdPregunta.Value] = examen.OpcionResp;
                confianzas[currentIdPregunta.Value] = examen.Confianza;

                @:<section id="p@examen.IdPregunta">
                @:<h3>@examen.IdPregunta - @examen.DescPregunta</h3>
            }

            @:<label class="opcion" data-pregunta="@examen.IdPregunta">
            @:<input type='radio' value='@examen.IdOpcion' name='@examen.IdPregunta' data-correcta='@examen.EsCorrecta' onclick='respuesta(@examen.IdPregunta, this)' @(respuestas[examen.IdPregunta] == examen.IdOpcion ? "checked" : "") />@examen.DescRespuesta
            @:</label>

            if (examen.EsCorrecta)
            {
                correctas[examen.IdPregunta] = examen.IdOpcion;
            }
        }

        @if (currentIdPregunta != null)
        {
            @:<div>

                <label style="text-align:center; font-weight: bold;">Nivel de confianza:</label>
                @for (int i = 1; i <= 3; i++)
                {
                    <label>
                        <input type="radio" name="confianza_@currentIdPregunta" value="@i" onclick="seleccionarConfianza(@currentIdPregunta, @i)" @(confianzas[currentIdPregunta.Value] == i ? "checked" : "") /> @(i == 1 ? "Baja" : i == 2 ? "Media" : "Alta")
                    </label>
                }
            @:</div>
            @:</section>
        }

        @if (Model.Calificacion == null)
        {
            <button id="corregirBtn" onclick="mostrarModal()" style="margin: 10px 10%;">Calificar</button>
            <button id="guardarRespuestasBtn" onclick="guardarRespuestas()" style="margin: 10px 10%;">GUARDAR RESPUESTAS</button>
            <h2>Cantidad acertadas: <span id="resultado"></span></h2>
        }
        else
        {
            <button id="corregirBtn"  onclick ="window.location.href='@Url.Action("Temas", "CuestionarioAlumnos")'"style="margin: 10px 10%;">Regresar</button>
        }

        
    </div>

    <!-- Modal -->
    <div id="myModal" class="popup">
        <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Warning.svg/2219px-Warning.svg.png" alt="Warning">
        <h2>Confirmar</h2>
        <p>¿Estás seguro de que deseas confirmar las respuestas? No podrás modificar las respuestas después de esto.</p>
        <button onclick="confirmarCorregir()">Sí, confirmar</button>
        <button class="cancel-btn" onclick="cerrarModal()">Cancelar</button>
    </div>

    <script>
        let correctas = @Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(correctas));
        let opcion_elegida = @Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(respuestas));
        let niveles_confianza = @Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(confianzas));
        let cantidad_correctas = 0;
        let userCorreo = "@ViewBag.UserCorreo";

        function respuesta(num_pregunta, seleccionada) {
            opcion_elegida[num_pregunta] = parseInt(seleccionada.value);

            let id = "p" + num_pregunta;
            let labels = document.getElementById(id).getElementsByTagName('label');
            for (let i = 0; i < labels.length; i++) {
                labels[i].style.backgroundColor = "white";
            }

            seleccionada.parentNode.style.backgroundColor = "#cec0fc";
        }

        function seleccionarConfianza(num_pregunta, confianza) {
            niveles_confianza[num_pregunta] = confianza;
        }

        // Botón para abrir el modal
        function mostrarModal() {
            document.getElementById("myModal").classList.add("open-popup");
        }

        // Función para cerrar el modal
        function cerrarModal() {
            document.getElementById("myModal").classList.remove("open-popup");
        }

        function confirmarCorregir() {
            cerrarModal();
            corregir();
        }

        function corregir() {
            cantidad_correctas = 0;
            for (let pregunta in opcion_elegida) {
                if (opcion_elegida.hasOwnProperty(pregunta)) {
                    let seleccionada = opcion_elegida[pregunta];
                    if (correctas[pregunta] === seleccionada) {
                        cantidad_correctas++;
                    }
                }
            }

            document.getElementById("resultado").innerHTML = cantidad_correctas;
            document.getElementById("guardarRespuestasBtn").style.display = "inline-block"; // Mostrar el botón "GUARDAR RESPUESTAS"
            document.getElementById("corregirBtn").style.display = "none"; // Ocultar el botón "CORREGIR"
        }

        function guardarRespuestas() {
            let respuestas = [];
            for (let pregunta in opcion_elegida) {
                if (opcion_elegida.hasOwnProperty(pregunta)) {
                    let seleccionada = opcion_elegida[pregunta];
                    respuestas.push({
                        IdPrueba: @Model.IdTema,
                        IdPregunta: parseInt(pregunta),
                        IdOpcion: seleccionada,
                        EsCorrecta: correctas[pregunta] === seleccionada,
                        Confianza: niveles_confianza[pregunta] || 0
                    });
                }
            }

            fetch('/ExamenAlumno/GuardarRespuestas', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify(respuestas)
            }).then(response => {
                if (response.ok) {
                    alert("Respuestas guardadas correctamente");
                    window.location.href = "@Url.Action("Temas", "CuestionarioAlumnos")";
                } else {
                    alert("Error al guardar respuestas");
                }
            });
        }

        // Cerrar el modal si el usuario hace clic fuera del modal
        window.onclick = function(event) {
            let modal = document.getElementById("myModal");
            if (event.target == modal) {
                modal.classList.remove("open-popup");
            }
        }
    </script>
</body>
</html>